### ISSUE TITLE
Leading text in file causes exception

### ISSUE THREAD

**Issue by zaneneuschuler** [garcia/simfile#41]
While using [nine or null](https://github.com/telperion/nine-or-null), for one particular file it would not be able to load. After looking through the files I found the issue:

```py
[2023-06-29 21:37:37.085] ERROR    stray 'x' encountered at start of document
Traceback (most recent call last):
  File "nine_or_null\__init__.py", line 729, in batch_process
  File "simfile\__init__.py", line 109, in open
  File "simfile\__init__.py", line 152, in open_with_detected_encoding
  File "simfile\__init__.py", line 83, in load
  File "simfile\base.py", line 164, in __init__
  File "simfile\ssc.py", line 217, in _parse
  File "msdparser\parser.py", line 103, in parse_msd
  File "msdparser\parser.py", line 72, in push_text
```

As it turns out, you can have leading text at the very top of a MSD file, and (at least tested on ITGMania, but this is such an edge case I wouldn't doubt it also works in sm5.1/etc) it will _still be usable in game_. However, since this is completely unexpected input from a proper file w/r/t this library, it throws an error.

**Comment by garcia** [comment]
This can be resolved on the application's side by opting into non-strict parsing. I've mentioned this to the maintainer and they said it would be fixed in the next release.
